# Generated by Django 3.0.5 on 2020-04-29 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desktop',
            name='status',
            field=models.CharField(choices=[('AVAIABLE', 'Item Ready To Be Purchased'), ('SOLD', 'Item is Sold'), ('RESTOCKING', 'Item Restocking in Few Days')], default='SOLD', max_length=100),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='status',
            field=models.CharField(choices=[('AVAIABLE', 'Item Ready To Be Purchased'), ('SOLD', 'Item is Sold'), ('RESTOCKING', 'Item Restocking in Few Days')], default='SOLD', max_length=100),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='status',
            field=models.CharField(choices=[('AVAIABLE', 'Item Ready To Be Purchased'), ('SOLD', 'Item is Sold'), ('RESTOCKING', 'Item Restocking in Few Days')], default='SOLD', max_length=100),
        ),
    ]
